# Generated by Django 5.0.6 on 2024-06-21 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('all', 'All'), ('web', 'WEB Development'), ('gamedev', 'Gamedev'), ('android', 'Android Development'), ('data_science', 'Data Science'), ('ml', 'Machine Learning'), ('devops', 'DevOps'), ('cyber_security', 'Cyber security'), ('testing', 'Testing')], default='all', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
