# Generated by Django 5.0.6 on 2024-06-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0003_alter_article_image_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('web', 'WEB Development'), ('gamedev', 'Gamedev'), ('mobile', 'Mobile Development'), ('data_science', 'Data Science'), ('ml', 'Machine Learning'), ('devops', 'DevOps'), ('cyber_security', 'Cyber security'), ('testing', 'Testing')], default='all', max_length=30),
        ),
    ]
