# Generated by Django 5.0.6 on 2024-07-05 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0006_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 13, 44, 31, 103278, tzinfo=datetime.timezone.utc)),
        ),
    ]
