# Generated by Django 5.0.6 on 2024-07-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0007_remove_comment_date_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
