# Generated by Django 5.0.6 on 2024-07-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0007_alter_article_options_article_date'),
        ('forum_app', '0008_remove_article_date'),
    ]

    operations = [
    ]
