# Generated by Django 5.0.6 on 2024-07-07 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0011_alter_article_date_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 15, 1, 7, 105943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 15, 1, 7, 105943, tzinfo=datetime.timezone.utc)),
        ),
    ]
